### ISSUE TITLE
Change the `refer.log` file path. Currently it is being saved within the directory where the app is being executed.

### ISSUE THREAD

**Issue by Feohr** [Feohr/refer#7]
Create a new directory `~/.config/refer`. Here, we'll possibly save any configs in future as well. For now, log file should go under this folder.

Additionally, add a few more logs for `debug`, `info` and `trace`.

**Comment by mtsalt** [comment]
I'd like to work on this issue. I plan to start working on it by the end of this week.

**Comment by Feohr** [comment]
@mtsalt Go ahead. If you wish, you can assign this issue to yourself.

Also, I was wondering that `$HOME/.cache/refer/log` seems more appropriate location to store logs.

**Comment by mtsalt** [comment]
@Feohr I agree with your suggestion.

I thought `$HOME/.refer/log/refer.log` was better, but `$HOME/.cache/refer/log/refer.log` is much better because, in this project, we don't need to store the log file for a long period.
